server:
  port: 8080
spring:
  application:
    name: api-gateway-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
logging:
  level:
    org:
      springframework:
        web: DEBUG
