spring:
  application:
    name: room-service
  batch:
    initialize-schema: always
  datasource:
    password: my-secret-pw
    url: jdbc:mysql://localhost:3306/rooms?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
server:
  port: 8085