spring:
  application:
    name: authentication-service
  batch:
    initialize-schema: always
  datasource:
    password: my-secret-pw
    url: jdbc:mysql://localhost:3306/authentication?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
app:
  jwtExpirationMs: 3600000
  jwtSecret: internetprovider
server:
  port: 8084
logging:
  level:
    org:
      springframework:
        web: DEBUG
